### ISSUE TITLE
PrimaryGeneratedColumn use

### ISSUE THREAD

**Issue by yangyuji** [WittBulter/koa-ts#7]
Type:
- [] Help   
Description:
PrimaryGeneratedColumn()
id: number
创建后的字段怎么变成了_id: Object('uuid')类型了？查找了typeorm没找到问题所在，望指教！

**Comment by WittBulter** [comment]
你用的是 `mongodb` 吗，如果是主键请用 `ObjectIdColumn`，参考 [mongodb](https://typeorm.io/#/mongodb)

**Comment by WittBulter** [comment]
@yangyuji 还有什么问题吗
