### ISSUE TITLE
help: mongodb如何分页查询

### ISSUE THREAD

**Issue by yangyuji** [WittBulter/koa-ts#8]
Type:
- [ ] Help   

Description:
使用mongodb如何分页查询，使用createQueryBuilder提示：Query Builder is not supported by MongoDB

**Comment by WittBulter** [comment]
与仓库无关

**Comment by l1shen** [comment]
可以使用 `typeorm` 的 `find` 自带的 `Option`

```
this.repository.find({ skip: 10, take: 10 })
```
