### ISSUE TITLE
help:如何加入token校验

### ISSUE THREAD

**Issue by yangyuji** [WittBulter/koa-ts#9]
Type:
- [x] Help   

Description:
按照你的代码组织，在哪里加入用户token校验比较好？
https://github.com/typestack/routing-controllers#using-authorization-features

**Comment by WittBulter** [comment]
1. 如果鉴权是全局或用的地方较多，可以放在 `configs` 下面。新建文件 `/configs/authorization.ts`：
```
export const AuthorizationChecker = ...
```

2. 在 `/configs/routing.options.ts` 中加入 (`CurrentUser` 同理):
```ts
import { AuthorizationChecker } from './authorization'

export const routingConfigs: RoutingControllersOptions = {
  //...
  authorizationChecker: AuthorizationChecker,
}
```

3. 如果只是为单个路由或某个子路由构建，复用较少的验证，可以写成 `Service` 或者 `UseBefore`。
